services:
  api:
    build: ./api
    ports:
      - "8080:8000"
    volumes:
      - ./api:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=sqlite:///app.db

  deploytrail:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    depends_on:
      - api